# Generated by Django 4.1.2 on 2023-05-26 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('danceapp', '0002_register_dance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='Time',
            field=models.DateTimeField(null=True),
        ),
    ]
