# Generated by Django 4.1.2 on 2023-05-26 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('danceapp', '0003_alter_events_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='date',
        ),
    ]
