# Generated by Django 4.1.2 on 2023-05-26 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('danceapp', '0004_remove_events_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sign_up',
            name='event',
        ),
    ]
