# Generated by Django 4.1.2 on 2023-05-26 19:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('danceapp', '0005_remove_sign_up_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='confirmed',
        ),
        migrations.AddField(
            model_name='events',
            name='confirmed_users',
            field=models.ManyToManyField(blank=True, related_name='confirmed_events', to=settings.AUTH_USER_MODEL),
        ),
    ]
