# Generated by Django 4.1.3 on 2023-05-31 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('danceapp', '0006_remove_events_confirmed_events_confirmed_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='confirmed_events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='danceapp.events')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='danceapp.sign_up')),
            ],
        ),
    ]
