# Generated by Django 4.1.3 on 2023-05-31 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('danceapp', '0007_confirmed_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmed_events',
            name='ontime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
